/**
 * Shared blog post components — the single source of truth for the markup that
 * every post's "post footer" region contains.
 *
 * Posts are standalone HTML files (no build step / no server-side templating),
 * so "template-driven" here means: this module renders the markup,
 * `scripts/sync_blog_components.ts` writes it into every post between the
 * BEGIN/END markers, and `blog_components_test.ts` fails if any post drifts.
 *
 * To add a post: add it to `blog_posts.ts`, add an entry here, run
 * `deno task sync:posts`. Never hand-edit the generated block in a post.
 */

import { BLOG_POSTS, type BlogPost } from "./blog_posts.ts";

/** Bumped whenever blog.css changes, so cached CSS can't hide a restyle. */
export const BLOG_CSS_VERSION = "13";
/** Bumped whenever blog/helpful.js changes. */
export const HELPFUL_JS_VERSION = "5";

/**
 * Blog index pages. They aren't posts — no components, no schema — but they do
 * load blog.css, so the sync script keeps their cache-bust versions current
 * along with the posts'.
 */
export const BLOG_INDEX_PAGES = ["/blog/", "/es/blog/"];

/**
 * Marker comments delimiting the generated region inside each post.
 * The sync script matches on the prefix so the trailing note can be reworded
 * without stranding already-generated blocks.
 */
export const BEGIN_MARKER_PREFIX = "<!-- BEGIN post-components";
export const BEGIN_MARKER =
  `${BEGIN_MARKER_PREFIX}: generated by scripts/sync_blog_components.ts — edit blog_components.ts, not this block -->`;
export const END_MARKER = "<!-- END post-components -->";

export interface PostComponents {
  /** Counterpart post path, or null when no translation exists yet. */
  altPath: string | null;
  /** Switcher copy; null when there is no counterpart. */
  switchCopy: { lead: string; anchor: string } | null;
  /** 5–8 post-specific schema.org keywords. */
  keywords: string;
  /**
   * schema.org `about` Thing names for this post. Kept in English on ES posts
   * too: these are entity names for crawlers, not reader-facing copy.
   */
  about: string[];
}

/**
 * Per-post configuration. Switcher copy stays contextual per post; the lead-in
 * is always written in the language it links to, so a reader scanning in their
 * own language spots it.
 */
export const POST_COMPONENTS: Record<string, PostComponents> = {
  "/blog/you-dont-have-to-sing-well/": {
    altPath: "/es/blog/cantarle-a-mi-bebe-si-canto-mal/",
    switchCopy: {
      lead: "También en español",
      anchor: "¿Cantarle a mi bebé si canto mal?",
    },
    keywords:
      "singing to your baby, infant-directed singing, parent voice preference, singing off key, bonding through music, toddler music development",
    about: ["Infant-directed singing", "Parent-child interaction"],
  },
  "/es/blog/cantarle-a-mi-bebe-si-canto-mal/": {
    altPath: "/blog/you-dont-have-to-sing-well/",
    switchCopy: {
      lead: "Also in English",
      anchor: "Why your toddler prefers your voice anyway",
    },
    keywords:
      "cantarle al bebé, cantar desafinado, voz de mamá y papá, canto dirigido a bebés, vínculo con la música, desarrollo musical infantil",
    about: ["Infant-directed singing", "Parent-child interaction"],
  },
  "/blog/toddler-screen-time-honest-take/": {
    altPath: "/es/blog/es-malo-youtube-para-ninos-pequenos/",
    switchCopy: {
      lead: "También en español",
      anchor: "¿Es malo YouTube para niños pequeños?",
    },
    keywords:
      "toddler screen time, screen time guidelines, kids YouTube, co-viewing with toddlers, video deficit effect, toddler media habits",
    about: ["Screen time", "Child development"],
  },
  "/es/blog/es-malo-youtube-para-ninos-pequenos/": {
    altPath: "/blog/toddler-screen-time-honest-take/",
    switchCopy: {
      lead: "Also in English",
      anchor: "An honest screen time take for toddler parents",
    },
    keywords:
      "tiempo de pantalla, YouTube para niños, pantallas en la primera infancia, ver videos en familia, recomendaciones de pantallas, niños pequeños y videos",
    about: ["Screen time", "Child development"],
  },
  "/blog/why-toddlers-want-the-same-song-on-repeat/": {
    altPath: "/es/blog/por-que-mi-hijo-quiere-la-misma-cancion/",
    switchCopy: {
      lead: "También en español",
      anchor: "Por qué mi hijo quiere la misma canción una y otra vez",
    },
    keywords:
      "toddler repetition, same song on repeat, repeated listening, word learning, memory consolidation, early language development",
    about: ["Language acquisition", "Repetition"],
  },
  "/es/blog/por-que-mi-hijo-quiere-la-misma-cancion/": {
    altPath: "/blog/why-toddlers-want-the-same-song-on-repeat/",
    switchCopy: {
      lead: "Also in English",
      anchor: "Why toddlers want the same song on repeat",
    },
    keywords:
      "repetición en niños, escuchar la misma canción, aprendizaje de palabras, memoria infantil, música para niños, desarrollo del lenguaje",
    about: ["Language acquisition", "Repetition"],
  },
  "/blog/teaching-toddlers-second-language-songs/": {
    altPath: "/es/blog/ensenar-ingles-a-ninos-con-canciones/",
    switchCopy: {
      lead: "También en español",
      anchor: "Enseñar inglés a niños con canciones",
    },
    keywords:
      "second language for toddlers, bilingual toddlers, songs for language learning, early language exposure, live interaction learning, Spanish songs for kids",
    about: ["Second-language acquisition", "Bilingualism"],
  },
  "/es/blog/ensenar-ingles-a-ninos-con-canciones/": {
    altPath: "/blog/teaching-toddlers-second-language-songs/",
    switchCopy: {
      lead: "Also in English",
      anchor: "Teaching your toddler a second language with songs",
    },
    keywords:
      "enseñar inglés a niños, canciones en inglés, bilingüismo temprano, exposición temprana al idioma, aprender inglés cantando, primera infancia",
    about: ["Second-language acquisition", "Bilingualism"],
  },
  "/blog/do-animal-sounds-count-as-words/": {
    altPath: "/es/blog/los-sonidos-de-animales-cuentan-como-palabras/",
    switchCopy: {
      lead: "También en español",
      anchor: "Los sonidos de animales cuentan como palabras",
    },
    keywords:
      "toddler language development, animal sounds, first words, onomatopoeia, speech milestones, farm songs for toddlers",
    about: ["Language acquisition", "Vocabulary development"],
  },
  "/es/blog/los-sonidos-de-animales-cuentan-como-palabras/": {
    altPath: "/blog/do-animal-sounds-count-as-words/",
    switchCopy: {
      lead: "Also in English",
      anchor: "Do animal sounds count as words?",
    },
    keywords:
      "desarrollo del lenguaje infantil, sonidos de animales, primeras palabras, onomatopeyas, hitos del habla, canciones de la granja",
    about: ["Language acquisition", "Vocabulary development"],
  },
  "/blog/alphabet-songs-for-toddlers/": {
    altPath: "/es/blog/canciones-del-abecedario-para-ninos/",
    switchCopy: {
      lead: "También en español",
      anchor: "Canciones del abecedario para niños",
    },
    keywords:
      "alphabet songs for toddlers, ABC song, letter recognition, early literacy, phonological awareness, teaching toddlers letters",
    about: ["Alphabet", "Early literacy"],
  },
  "/es/blog/canciones-del-abecedario-para-ninos/": {
    altPath: "/blog/alphabet-songs-for-toddlers/",
    switchCopy: {
      lead: "Also in English",
      anchor: "How toddlers really learn their ABCs",
    },
    keywords:
      "canciones del abecedario, canción del ABC, reconocer letras, lectoescritura temprana, conciencia fonológica, enseñar letras a niños",
    about: ["Alphabet", "Early literacy"],
  },
  "/blog/bedtime-songs-for-toddlers/": {
    altPath: "/es/blog/canciones-para-dormir-ninos/",
    switchCopy: {
      lead: "También en español",
      anchor: "Canciones para dormir niños",
    },
    keywords:
      "bedtime songs for toddlers, lullabies, toddler sleep routine, wind-down routine, calming music for kids, bedtime resistance",
    about: ["Sleep", "Bedtime routines"],
  },
  "/es/blog/canciones-para-dormir-ninos/": {
    altPath: "/blog/bedtime-songs-for-toddlers/",
    switchCopy: {
      lead: "Also in English",
      anchor: "Build a musical bedtime wind-down that works",
    },
    keywords:
      "canciones para dormir niños, nanas para bebés, rutina de sueño infantil, música tranquila para dormir, canciones de cuna, hora de dormir sin batallas",
    about: ["Sleep", "Bedtime routines"],
  },
  "/blog/songs-to-teach-toddlers-colors/": {
    altPath: "/es/blog/canciones-de-colores-para-ninos/",
    switchCopy: {
      lead: "También en español",
      anchor: "Canciones de colores para niños",
    },
    keywords:
      "songs to teach colors, color recognition, toddler learning activities, color songs for kids, learning through play, music and early learning",
    about: ["Language acquisition", "Teaching colors"],
  },
  "/es/blog/canciones-de-colores-para-ninos/": {
    altPath: "/blog/songs-to-teach-toddlers-colors/",
    switchCopy: {
      lead: "Also in English",
      anchor: "7 ways to teach toddlers colors with songs",
    },
    keywords:
      "canciones de colores, enseñar colores a niños, reconocer colores, actividades para niños pequeños, aprender jugando, música y aprendizaje temprano",
    about: ["Language acquisition", "Teaching colors"],
  },
};

/** Posts still waiting on a translation — surfaced as a content TODO, never invented. */
export function postsMissingTranslation(): BlogPost[] {
  return BLOG_POSTS.filter((p) => POST_COMPONENTS[p.path]?.altPath == null);
}

/** Helpful-API slug for a post path: `/blog/foo/` -> `blog/foo`. */
export function helpfulSlugForPath(path: string): string {
  return path.replace(/^\/+/, "").replace(/\/+$/, "");
}

/** Repo-relative HTML file for a post path. */
export function fileForPath(path: string): string {
  return `.${path}index.html`;
}

const HELPFUL_COPY = {
  en: {
    ariaLabel: "Mark this post as helpful",
    label: "This helped",
  },
  es: {
    ariaLabel: "Marcar este artículo como útil",
    label: "Esto ayudó",
  },
} as const;

function indentLines(html: string, indent: string): string {
  return html
    .split("\n")
    .map((line) => (line.length > 0 ? indent + line : line))
    .join("\n");
}

/**
 * schema.org `about` array, formatted to match the hand-written JSON-LD in the
 * existing posts (4-space nesting, trailing comma so it can precede a sibling).
 */
export function renderSchemaAbout(names: string[], indent: string): string {
  const things = names.map((name) =>
    [
      `${indent}    {`,
      `${indent}        "@type": "Thing",`,
      `${indent}        "name": "${name}"`,
      `${indent}    }`,
    ].join("\n")
  );
  return [
    `${indent}"about": [`,
    things.join(",\n"),
    `${indent}],`,
  ].join("\n");
}

/** Contextual EN<->ES switcher. Empty string when no counterpart exists. */
export function renderLangSwitch(post: BlogPost): string {
  const config = POST_COMPONENTS[post.path];
  if (!config?.altPath || !config.switchCopy) return "";
  const targetLang = post.lang === "en" ? "es" : "en";
  const { lead, anchor } = config.switchCopy;
  return [
    `<p class="blog-lang-switch" lang="${targetLang}">${lead} &rarr; ` +
    `<a href="${config.altPath}" hreflang="${targetLang}" lang="${targetLang}">${anchor}</a></p>`,
  ].join("\n");
}

/** Thumbs-up "this helped" control. Reuses the existing /api/helpful counter. */
export function renderHelpfulWidget(post: BlogPost): string {
  const copy = HELPFUL_COPY[post.lang];
  const slug = helpfulSlugForPath(post.path);
  return [
    `<div class="blog-helpful" data-helpful data-lang="${post.lang}" data-slug="${slug}">`,
    `    <button type="button" class="blog-helpful-btn" aria-label="${copy.ariaLabel}">`,
    `        <picture>`,
    `            <source type="image/webp" srcset="/blog/zaydio-thumbs-up-128.webp 1x, /blog/zaydio-thumbs-up-256.webp 2x, /blog/zaydio-thumbs-up-512.webp 4x">`,
    `            <img class="blog-helpful-thumb" src="/blog/zaydio-thumbs-up-256.png" width="64" height="128" alt="" aria-hidden="true" loading="lazy" decoding="async">`,
    `        </picture>`,
    `    </button>`,
    `    <span class="blog-helpful-label">${copy.label}</span>`,
    `    <p class="blog-helpful-count" hidden></p>`,
    `    <canvas class="blog-helpful-confetti" aria-hidden="true"></canvas>`,
    `</div>`,
  ].join("\n");
}

/**
 * The full generated region: switcher then like button, at one consistent
 * position — end of the post body, before the signup box and Sources.
 */
export function renderPostComponents(post: BlogPost, indent = ""): string {
  const parts = [renderLangSwitch(post), renderHelpfulWidget(post)].filter(
    (p) => p.length > 0,
  );
  const body = parts.join("\n\n");
  return [
    indent + BEGIN_MARKER,
    indentLines(body, indent),
    indent + END_MARKER,
  ].join("\n");
}
